version: '3.8'

services:
  siba-fe-nginx:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: siba_fe_nginx_container
    ports:
      - '${PORT}:8080'