services:
  siba-fe-nginx:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: siba_fe_nginx_container
    ports:
      - "${PORT}:80"
      - "${SSL_PORT}:443"
    volumes:
      - "${SSL_CERT_PATH}:/etc/nginx/ssl/fullchain.pem"
      - "${SSL_KEY_PATH}:/etc/nginx/ssl/privkey.pem"