version: "3.8"
services:
  siba-fe:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: siba_fe
    env_file: .env
    ports:
      - '${PORT}:${PORT}'
    stdin_open: true
    tty: true
