#!/bin/sh
FILES=$(git diff --cached --name-only | grep 'src/.*\.(js|ts)$')

if [ -n "$FILES" ]; then
    rome format $FILES --write --indent-style space --indent-size 2
    rome check $FILES --apply-suggested
    git add $FILES
else
    echo "No files to format"
fi
